export const PROTOCOL_COMMANDS = [
  'download',
  'encrypt',
  'encryptFile',
  'decryptDDO',
  'getDDO',
  'query',
  'nonce',
  'status',
  'detailedStatus',
  'findDDO',
  'getFees',
  'fileInfo',
  'validateDDO',
  'getComputeEnvironments',
  'startCompute',
  'freeStartCompute',
  'stopCompute',
  'getComputeStatus',
  'getComputeStreamableLogs',
  'getComputeResult',
  'initializeCompute',
  'stopNode',
  'reindexTx',
  'reindexChain',
  'handleIndexingThread',
  'collectFees',
  'PolicyServerPassthrough',
  'getP2PPeer',
  'getP2PPeers',
  'getP2PNetworkStats',
  'findPeer',
  'createAuthToken',
  'invalidateAuthToken',
  'fetchConfig',
  'pushConfig',
  'getLogs',
  'jobs',
  'persistentStorageCreateBucket',
  'persistentStorageGetBuckets',
  'persistentStorageListFiles',
  'persistentStorageUploadFile',
  'persistentStorageGetFileObject',
  'persistentStorageDeleteFile'
] as const

export type ProtocolCommand = (typeof PROTOCOL_COMMANDS)[number]

export const COMMAND_GROUPS: Record<string, ProtocolCommand[]> = {
  accessAndMetadata: [
    'download',
    'decryptDDO',
    'getDDO',
    'query',
    'findDDO',
    'validateDDO',
    'fileInfo',
    'getFees',
    'nonce'
  ],
  crypto: ['encrypt', 'encryptFile'],
  status: ['status', 'detailedStatus'],
  compute: [
    'getComputeEnvironments',
    'initializeCompute',
    'startCompute',
    'freeStartCompute',
    'stopCompute',
    'getComputeStatus',
    'getComputeResult',
    'getComputeStreamableLogs'
  ],
  p2p: ['getP2PPeer', 'getP2PPeers', 'getP2PNetworkStats', 'findPeer'],
  auth: ['createAuthToken', 'invalidateAuthToken'],
  admin: [
    'stopNode',
    'reindexTx',
    'reindexChain',
    'handleIndexingThread',
    'collectFees',
    'fetchConfig',
    'pushConfig',
    'getLogs',
    'jobs'
  ],
  persistentStorage: [
    'persistentStorageCreateBucket',
    'persistentStorageGetBuckets',
    'persistentStorageListFiles',
    'persistentStorageUploadFile',
    'persistentStorageGetFileObject',
    'persistentStorageDeleteFile'
  ]
}
